#!/bin/sh
if git rev-parse --verify HEAD >/dev/null>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
    exit 0
fi

changed_files=$(git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp|inl)$')
lint_ret=0
if [ -n "$changed_files" ]; then
    for file in $changed_files
    do
        clang-format --style=file -i $file
        cpplint CPPLINT.cfg $file
        if [ "$lint_ret" != "$?" ]; then  
            echo "[code style check failed]"
            exit 1
        fi
        git add $file
    done
fi